[profile.default]
src = "src"
libs = ["lib"]

remappings = [
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "tokenized-strategy/=lib/tokenized-strategy/",
    "@uniswap/v4-core/=lib/uniswap-v4-core/",
    "uniswap-hooks/=lib/uniswap-hooks/",
    "forge-std/=lib/forge-std/src/"
]
